name: Flask CI with Docker

on:
  push:
    branches:
      - "**"   # runs on every branch push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t flask-app:ci .

      # Step 4: Run pytest inside container
      - name: Run unit tests
        run: docker run --rm flask-app:ci pytest
